# api/student/one/:idUniversity
POST {{url}}api/student/one/1?idGroup=2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "gosha@gmail.com"
}

###
# api/student/:idUniversity
GET {{url}}api/student/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
# api/student/:idStudent
DELETE {{url}}api/student/12
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
# api/student/:idStudent
PATCH {{url}}api/student/10
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "groupId": 3
}
