POST {{url}}api/university?id=4
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "university_name": "Національний університет 'Одеська політехніка'",
  "university_short_name": "НУОП"
}

###
PATCH {{url}}api/university/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
"registration_year": 1999
}

###

# api/university/admin/:idUniversity
POST {{url}}api/university/admin/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "fredy@gmail.com"
}


