GET {{url}}api/user
Accept: application/json
Authorization: Bearer {{accessToken}}

###
PATCH {{url}}api/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
"sex": 0
}

###
# Login
POST {{url}}api/auth/login
Content-Type: application/json

{
  "email": "alexei@gmail.com",
  "password": "Qawsed123"
}

> {%
  console.log(response.body);
  client.global.set("accessToken", response.body.accessToken);
  client.global.set("refreshToken", response.body.refreshToken);
%}

###
# Refresh
GET {{url}}api/auth/refresh
Content-Type: application/json
Access-Control-Allow-Credentials: true
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZyZWR5QGdtYWlsLmNvbSIsImlkIjo4LCJpYXQiOjE3MjE5OTEyMTcsImV4cCI6MTc1MzUyNzIxN30.5jLkjd8itzVIaUJHW47cQ_ABP8qkvTOFomTinq4D9vA

> {%
  client.global.set("accessToken", response.body.accessToken);
  client.global.set("refreshToken", response.body.refreshToken);
%}

###
# Register
POST {{url}}api/auth/register
Content-Type: application/json

{
  "email": "pawel@gmail.com",
  "password": "Qawsed123",
  "firstName": "Pawel",
  "lastName": "Petrenko"
}
